# Generated by Django 4.2.2 on 2023-07-02 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Liked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Mypage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainImage', models.ImageField(null=True, upload_to='mypage/')),
                ('subImage1', models.ImageField(null=True, upload_to='mypage/')),
                ('subImage2', models.ImageField(null=True, upload_to='mypage/')),
                ('subImage3', models.ImageField(null=True, upload_to='mypage/')),
            ],
        ),
        migrations.CreateModel(
            name='MypageArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(null=True, upload_to='mypage/articleImage/')),
                ('mypage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='myPage.mypage')),
            ],
        ),
    ]
