# Generated by Django 4.2.2 on 2023-06-27 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='hit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
