# Generated by Django 4.2.2 on 2023-06-30 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_bloglike_delete_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='post',
            new_name='blog',
        ),
    ]
